-- CRIAR BANCO DE DADOS
CREATE DATABASE LOJA_INFORMATICA;

-- ATIVAR BD
USE LOJA_INFORMATICA;

CREATE TABLE PRODUTOS (
COD_PRODUTO INT,
DESCRICAO VARCHAR(255),
NOME_PRODUTO VARCHAR(100),
PRECO_PRODUTO DECIMAL,
IMAGEM BLOB
);


