CREATE DATABASE SOLAR;
USE SOLAR;

CREATE TABLE IF NOT EXISTS CLIENTES  (
COD_CLIENTE INT NOT NULL,
NOME_CLIENTE VARCHAR(100),
CPF VARCHAR(14) NOT NULL,
ENDERECO VARCHAR(100),
CELULAR VARCHAR(19),
PRIMARY KEY (COD_CLIENTE)
);

CREATE TABLE IF NOT EXISTS FORNECEDOR (
COD_FORNECEDOR INT NOT NULL,
NOME_FORNECEDOR VARCHAR(255),
CNPJ VARCHAR(18) NOT NULL,
ESTADO CHAR(2) DEFAULT 'SP' NOT NULL,
CIDADE VARCHAR(100) NOT NULL,
ENDERECO VARCHAR(100) NOT NULL,
COD_VENDA INT,
PRIMARY KEY (COD_FORNECEDOR,COD_VENDA)
);

CREATE TABLE PRODUTOS (
COD_PRODUTO INT AUTO_INCREMENT NOT NULL,
NOME_PRODUTO VARCHAR(100) NOT NULL,
DESCRICAO VARCHAR(100),
QTDE INT NOT NULL,
VALOR DECIMAL(5,2) NOT NULL,
PRIMARY KEY (COD_PRODUTO)
);

CREATE TABLE VENDA (
COD_VENDA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
COD_PRODUTO INT NOT NULL,
COD_FORNECEDOR INT NOT NULL,
FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTOS (COD_PRODUTO),
FOREIGN KEY (COD_FORNECEDOR) REFERENCES FORNECEDOR (COD_FORNECEDOR)
);

DROP TABLE FUNCIONARIOS;
-- CONSULTAR TABELAS
SELECT * FROM CLIENTES;

-- CRIAR AS ENTIDADES FUNCIONARIOS, DEPARTAMENTO
CREATE TABLE FUNCIONARIOS (
COD_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOME_FUNCIONARIO VARCHAR(100) NOT NULL,
CPF_FUNCIONARIO VARCHAR(14) NOT NULL,
ENDERECO_FUNCIONARIO VARCHAR(100) NOT NULL,
DATA_NASCIMENTO DATETIME NOT NULL,
DATA_ADMISSAO DATETIME NOT NULL,
DATA_RECISAO DATETIME NOT NULL,
SALARIO DECIMAL(7,2) NOT NULL,
COD_DEPARTAMENTO INT NOT NULL,
FOREIGN KEY (COD_DEPARTAMENTO) REFERENCES DEPARTAMENTO (COD_DEPARTAMENTO)
);

CREATE TABLE DEPARTAMENTO (
COD_DEPARTAMENTO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOME_DEPARTAMENTO VARCHAR(20) NOT NULL,
RESPONSÁVEL VARCHAR(100) NOT NULL,
SETOR VARCHAR(50) NOT NULL
);

-- CONSULTAR TABELA FUNCIONARIOS
SELECT * FROM EMPREGADO;

-- ALTERAÇÕES EM TABELAS
ALTER TABLE FUNCIONARIOS
ADD SEXO CHAR(1);

ALTER TABLE FUNCIONARIOS
DROP COLUMN SEXO;

ALTER TABLE FUNCIONARIOS
RENAME TO EMPREGADO;

DROP TABLE EMPREGADO;

ALTER TABLE EMPREGADO
CHANGE CPF_FUNCIONARIO CIC_FUNCIONARIO VARCHAR(18);

ALTER TABLE EMPREGADO
MODIFY COLUMN NOME_FUNCIONARIO VARCHAR(200);

ALTER TABLE FORNECEDORES
MODIFY COLUMN ESTADO CHAR(2) DEFAULT 'MG';

-- ALTERAR CHAVE PRIMÁRIA
ALTER TABLE EMPREGADO MODIFY CPF_FUNCIONARIO INT NOT NULL;
ALTER TABLE EMPREGADO DROP PRIMARY KEY;

ALTER TABLE EMPREGADO
ADD PRIMARY KEY (COD_FUNCIONARIO,CPF_FUNCIONARIO);



